/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 book.glb -T 
Files: book.glb [2.18MB] > C:\Users\Pedro\Desktop\macbook_gsap_app\public\models\book-transformed.glb [61.48KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Book(props) {
  const { nodes, materials } = useGLTF('/models/book-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane019.geometry} material={materials['Material.002']} position={[0.086, 0.077, 0.04]} rotation={[-0.765, 0.927, -0.41]} />
      <mesh geometry={nodes.sites.geometry} material={materials['Material.001']} position={[0.29, 0.306, 0.375]} rotation={[0.472, -0.241, -0.968]} />
    </group>
  )
}

useGLTF.preload('/models/book-transformed.glb')
